PROGRAMMING_LANGUAGES = {
    'python': 'Python',
    'javascript': 'JavaScript',
    'js': 'JavaScript',
    'typescript': 'TypeScript',
    'ts': 'TypeScript',
    'java': 'Java',
    'c++': 'C++',
    'cpp': 'C++',
    'c#': 'C#',
    'csharp': 'C#',
    'c': 'C',
    'go': 'Go',
    'golang': 'Go',
    'rust': 'Rust',
    'ruby': 'Ruby',
    'php': 'PHP',
    'swift': 'Swift',
    'kotlin': 'Kotlin',
    'scala': 'Scala',
    'r': 'R',
    'matlab': 'MATLAB',
    'perl': 'Perl',
    'lua': 'Lua',
    'dart': 'Dart',
    'elixir': 'Elixir',
    'haskell': 'Haskell',
    'groovy': 'Groovy',
    'objective-c': 'Objective-C',
    'bash': 'Bash',
    'shell scripting': 'Shell Scripting',
    'powershell': 'PowerShell',
    'vba': 'VBA',
    'visual basic': 'Visual Basic',
}

WEB_FRAMEWORKS = {
    'react': 'React',
    'reactjs': 'React',
    'react.js': 'React',
    'angular': 'Angular',
    'angularjs': 'Angular',
    'vue': 'Vue.js',
    'vue.js': 'Vue.js',
    'vuejs': 'Vue.js',
    'vuetify': 'Vuetify',
    'svelte': 'Svelte',
    'next.js': 'Next.js',
    'nextjs': 'Next.js',
    'nuxt': 'Nuxt.js',
    'nuxt.js': 'Nuxt.js',
    'gatsby': 'Gatsby',
    'express': 'Express.js',
    'express.js': 'Express.js',
    'expressjs': 'Express.js',
    'node': 'Node.js',
    'node.js': 'Node.js',
    'nodejs': 'Node.js',
    'node js': 'Node.js',
    'django': 'Django',
    'flask': 'Flask',
    'fastapi': 'FastAPI',
    'spring': 'Spring',
    'spring boot': 'Spring Boot',
    'rails': 'Ruby on Rails',
    'ruby on rails': 'Ruby on Rails',
    'laravel': 'Laravel',
    'asp.net': 'ASP.NET',
    '.net': '.NET',
    '.net core': '.NET Core',
    'dotnet': '.NET',
    'jquery': 'jQuery',
    'bootstrap': 'Bootstrap',
    'tailwind': 'Tailwind CSS',
    'tailwind css': 'Tailwind CSS',
    'material ui': 'Material UI',
    'redux': 'Redux',
    'webpack': 'Webpack',
    'vite': 'Vite',
    'ionic': 'Ionic',
    'wordpress': 'WordPress',
}

DATABASES = {
    'sql': 'SQL',
    'mysql': 'MySQL',
    'postgresql': 'PostgreSQL',
    'postgres': 'PostgreSQL',
    'sqlite': 'SQLite',
    'mongodb': 'MongoDB',
    'mongo': 'MongoDB',
    'redis': 'Redis',
    'elasticsearch': 'Elasticsearch',
    'cassandra': 'Cassandra',
    'dynamodb': 'DynamoDB',
    'firebase': 'Firebase',
    'firestore': 'Firestore',
    'neo4j': 'Neo4j',
    'oracle': 'Oracle DB',
    'mariadb': 'MariaDB',
    'supabase': 'Supabase',
    'sql server': 'SQL Server',
}

CLOUD_AND_DEVOPS = {
    'aws': 'AWS',
    'amazon web services': 'AWS',
    'azure': 'Azure',
    'microsoft azure': 'Azure',
    'gcp': 'Google Cloud',
    'google cloud': 'Google Cloud',
    'google cloud platform': 'Google Cloud',
    'docker': 'Docker',
    'kubernetes': 'Kubernetes',
    'k8s': 'Kubernetes',
    'terraform': 'Terraform',
    'ansible': 'Ansible',
    'jenkins': 'Jenkins',
    'ci/cd': 'CI/CD',
    'github actions': 'GitHub Actions',
    'gitlab ci': 'GitLab CI',
    'nginx': 'Nginx',
    'apache': 'Apache',
    'linux': 'Linux',
    'ubuntu': 'Ubuntu',
    'heroku': 'Heroku',
    'vercel': 'Vercel',
    'netlify': 'Netlify',
    'serverless': 'Serverless',
}

DATA_SCIENCE_AND_ML = {
    'machine learning': 'Machine Learning',
    'ml': 'Machine Learning',
    'deep learning': 'Deep Learning',
    'dl': 'Deep Learning',
    'artificial intelligence': 'Artificial Intelligence',
    'ai': 'Artificial Intelligence',
    'nlp': 'NLP',
    'natural language processing': 'NLP',
    'computer vision': 'Computer Vision',
    'tensorflow': 'TensorFlow',
    'pytorch': 'PyTorch',
    'keras': 'Keras',
    'scikit-learn': 'Scikit-learn',
    'sklearn': 'Scikit-learn',
    'pandas': 'Pandas',
    'numpy': 'NumPy',
    'scipy': 'SciPy',
    'matplotlib': 'Matplotlib',
    'seaborn': 'Seaborn',
    'plotly': 'Plotly',
    'tableau': 'Tableau',
    'power bi': 'Power BI',
    'jupyter': 'Jupyter',
    'spacy': 'spaCy',
    'hugging face': 'Hugging Face',
    'transformers': 'Transformers',
    'bert': 'BERT',
    'gpt': 'GPT',
    'llm': 'LLM',
    'large language models': 'LLM',
    'langchain': 'LangChain',
    'openai': 'OpenAI',
    'opencv': 'OpenCV',
    'data analysis': 'Data Analysis',
    'data visualization': 'Data Visualization',
    'data engineering': 'Data Engineering',
    'data science': 'Data Science',
    'neural networks': 'Neural Networks',
    'cnn': 'CNN',
    'rnn': 'RNN',
    'lstm': 'LSTM',
    'xgboost': 'XGBoost',
    'random forest': 'Random Forest',
    'reinforcement learning': 'Reinforcement Learning',
}

TOOLS_AND_VERSION_CONTROL = {
    'git': 'Git',
    'github': 'GitHub',
    'gitlab': 'GitLab',
    'bitbucket': 'Bitbucket',
    'jira': 'Jira',
    'confluence': 'Confluence',
    'trello': 'Trello',
    'figma': 'Figma',
    'postman': 'Postman',
    'swagger': 'Swagger',
    'adobe illustrator': 'Adobe Illustrator',
    'adobe xd': 'Adobe XD',
    'photoshop': 'Photoshop',
    'autocad': 'AutoCAD',
    'google apps script': 'Google Apps Script',
    'google app script': 'Google Apps Script',
}

APIS_AND_PROTOCOLS = {
    'rest api': 'REST API',
    'restapi': 'REST API',
    'rest': 'REST API',
    'graphql': 'GraphQL',
    'grpc': 'gRPC',
    'websocket': 'WebSocket',
    'websockets': 'WebSocket',
    'oauth': 'OAuth',
    'jwt': 'JWT',
    'soap': 'SOAP',
}

WEB_FUNDAMENTALS = {
    'html': 'HTML',
    'html5': 'HTML',
    'css': 'CSS',
    'css3': 'CSS',
    'sass': 'SASS',
    'less': 'LESS',
    'seo': 'SEO',
}

TESTING = {
    'pytest': 'Pytest',
    'jest': 'Jest',
    'mocha': 'Mocha',
    'cypress': 'Cypress',
    'selenium': 'Selenium',
    'unit testing': 'Unit Testing',
}

MOBILE = {
    'react native': 'React Native',
    'flutter': 'Flutter',
    'android': 'Android',
    'android studio': 'Android Studio',
    'ios': 'iOS',
    'xamarin': 'Xamarin',
}

SECURITY = {
    'ethical hacking': 'Ethical Hacking',
    'cybersecurity': 'Cybersecurity',
    'kali linux': 'Kali Linux',
    'nmap': 'Nmap',
    'burpsuite': 'Burp Suite',
    'burp suite': 'Burp Suite',
    'wireshark': 'Wireshark',
    'nessus': 'Nessus',
    'owasp': 'OWASP',
    'penetration testing': 'Penetration Testing',
}

METHODOLOGIES = {
    'agile': 'Agile',
    'scrum': 'Scrum',
    'kanban': 'Kanban',
    'devops': 'DevOps',
    'microservices': 'Microservices',
    'oop': 'OOP',
    'design patterns': 'Design Patterns',
    'data structures': 'Data Structures',
    'algorithms': 'Algorithms',
}

SKILLS_DATABASE = {
    **PROGRAMMING_LANGUAGES,
    **WEB_FRAMEWORKS,
    **DATABASES,
    **CLOUD_AND_DEVOPS,
    **DATA_SCIENCE_AND_ML,
    **TOOLS_AND_VERSION_CONTROL,
    **APIS_AND_PROTOCOLS,
    **WEB_FUNDAMENTALS,
    **TESTING,
    **MOBILE,
    **SECURITY,
    **METHODOLOGIES,
}
